### ISSUE TITLE
what is this thing?

### ISSUE THREAD

**Issue by PeppoNetwork** [Crystallinqq/FutureClient-Auth#4]
anyways cool, phobos stronk

now how do i use this thing?

**Comment by Gopro336** [comment]
its not intended to be used

**Comment by Katatje** [comment]
i use this

**Comment by Crystallinqq** [comment]
its for learning.

**Comment by PeppoNetwork** [comment]
> its for learning.

Hey crystallinqq, mind if you give me your discord so we can talk?

**Comment by Crystallinqq** [comment]
@PeppoNetwork about what.

**Comment by kylerittenhause** [comment]
> > its for learning.
> 
> Hey crystallinqq, mind if you give me your discord so we can talk?

benis

**Comment by qzqn** [comment]
bull shit

**Comment by x4e** [comment]
> > its for learning.
> 
> Hey crystallinqq, mind if you give me your discord so we can talk?

Crystallinqq's discord account is `mastercooker#7021`

**Comment by Crystallinqq** [comment]
> > > its for learning.
> > 
> > 
> > Hey crystallinqq, mind if you give me your discord so we can talk?
> 
> Crystallinqq's discord account is `mastercooker#7021`

um no this is actually cookiedragon234’s discord......

**Comment by x4e** [comment]
who?

**Comment by x4e** [comment]
> > > > its for learning.
> > > 
> > > 
> > > Hey crystallinqq, mind if you give me your discord so we can talk?
> > 
> > 
> > Crystallinqq's discord account is `mastercooker#7021`
> 
> um no this is actually cookiedragon234’s discord......

no

**Comment by Crystallinqq** [comment]
:(
